### ISSUE TITLE
To go OSS all the way, consider deploying to a parse server instead of firebase

### ISSUE THREAD

**Issue by lucasverra** [kefranabg/bento-starter#138]
Firebase is vendor lock-in. It is not OSS. 

**Describe the solution you'd like**
As [parse server project is indeed OSS](https://github.com/parse-community) and fully maintained, wouldn't make sense to deploy ins a Parse server instance? 

**Additional context**
My startup is based on Parse server and it provides ~95% of the same features. I'm not a developer so i cannot measure the complexity of this feature.

**Comment by kefranabg** [comment]
Hi @lucasverra 

From what I've seen, parse server would just add complexity to the stack because you need to take care of a server instance and it would introduce an extra component in the bento-starter stack.

**bento-starter** produces only static content, and it's really simple to deliver it through firebase hosting.

When you say that Firebase is not OSS, you're talking about the hosting part ?

I appreciate the suggestion though 😉

**Comment by lucasverra** [comment]
> When you say that Firebase is not OSS, you're talking about the hosting part ?

I mean just that yeah. 

The day Google want's your app off, there is no migration. I just can't take my app with me. 

parse server project, on the other hand, you can host [it on any cloud provider](https://bitnami.com/stack/parse/cloud), with more or less mess on your hand regarding hosting indeed.

**Comment by kefranabg** [comment]
I'm not sure you're understanding how bento-starter works.

> parse server project, on the other hand, you can host it on any cloud provider, with more or less mess on your hand regarding hosting indeed.

Using parse server won't solve this problem. As I said, bento-starter generates static content, it can be deployed on any CDN. We don't need server...

> The day Google want's your app off, there is no migration process. I just can't take my app with me.

The day Google give up firebase, the problem won't be the hosting. The problem will be data management currently handled with Firestore.

In addition, I'm not a big fan of your point of view. I like cloud/serverless solutions because they help me to focus other important parts. 

I'll close this issue as your feature request does not match the project's philosophy.
Thanks for your interest !

**Comment by lucasverra** [comment]
> The day Google give up firebase, the problem won't be the hosting. The problem will be data management currently handled with Firestore.

I always meant hosting of the data (firestore) with `vendor lock-in`. Even Today to get your data out, you need the provide [billing info](https://firebase.google.com/docs/firestore/manage-data/export-import#before_you_begin) 

> In addition, I'm not a big fan of your point of view. I like cloud/serverless solutions because it helps me to focus on other important project parts.

100% agree with you. Parse server [is serverless](http://docs.parseplatform.org/cloudcode/guide/) computing.

Don't get me wrong, I like your project's philosophy. That is why I truly believe that it fits Parse server OSS ecosystem. 
I understand that it's probably not your priority to remove Google footprint in this project, but if you know that other solutions currently exist, then the issue is solved 😉

Congrats on launch ✌🏼
