### ISSUE TITLE
Using Unix comands in setup script causes Windows run setup to fail 

### ISSUE THREAD

**Issue by perkinsjr** [kefranabg/bento-starter#191]
**Describe the bug**
When creating a fresh bento starter, on a windows machine. When you check out and run the npm run setup in Vscode it causes the job to fail due to UNIX commands.
**To Reproduce**
1. Check out clean copy
2. Run npm run setup from vscode or command line
3. Select Y when asked about new repo
4. Error; Error: Command failed rm -Rf .git

**Expected behavior**
A user shouldn't be expected to use git bash or similar UNIX wrapper on a windows machine to get started. You should stop using rimraf and do an OS check. If UNIX use 'rm -rf' as its more efficient than rimraf and then use the rd /s /q "path" for windows. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise / VSCODE June release
 - Browser N/A
 - Version N/A

**Additional context**
This works fine from git bash, or similar wrapper. Fails on vscode using windows command prompt. 

See below for error:

![2019-06-13 08_30_04-Window](https://user-images.githubusercontent.com/45409975/59432513-7c913980-8db5-11e9-965f-238b86db6922.png)

**Comment by kefranabg** [comment]
Hi @perkinsjr, thanks for this clean report !
Are you interested in providing an implementation in a pull request ?

**Comment by perkinsjr** [comment]
@kefranabg Of course. 

I will work on it over the weekend.

**Comment by kefranabg** [comment]
Thanks 🙏 😃 !

**Comment by perkinsjr** [comment]
@kefranabg  Fixed with latest commit to Pull Request I had out there for email and password. The change is a 3 lines check against the os.platform and then use a windows command if its windows as the problem child was in the git-helper and not were I originally thought

**Comment by tbetous** [comment]
Hi @perkinsjr !

Thanks a lot for your contribution. I think you should solve the problem in a separate PR instead of inside your previous PR (#182). We currently discuss with @kefranabg  about the #179 and we are not sure if we want or not this feature in bento-starter. Your code hasn't been useless because it allowed us to make a step forward into our tought about this feature. We just need time !

But come back to the #191 ! I saw your implementation, did you try to use rimraf that we already use for deleting useless resources in `clean-useless-resources.js` ? I think the best way to solve this bug is to change `removeGitRepository()` in `git-helper.js` like you did, but with rimraf instead os. What do you think about that ?

**Comment by perkinsjr** [comment]
@tbetous  thanks for the words. Yes @kefranabg and I discussed the same things previously in the PR and the changes are now avail. 

Cheers
