### ISSUE TITLE
Overide env variable with `.env.local`

### ISSUE THREAD

**Issue by antoinecellier** [kefranabg/bento-starter#204]
**Describe the bug**
Hey ! 
I try to overide env variable with `.env.local` file. 

**To Reproduce**
Steps to reproduce the behavior
1. Set variable in `.env` file: `VUE_APP_TITLE=Readable Changelog`
2. Create `.env.local` file in root folder
3. Add variable in this file: `VUE_APP_TITLE=Readable Changelog Local`
4. Launch development server= `yarn serve`

**Expected behavior**
`VUE_APP_TITLE` value is already `Readable Changelog`
 

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.4
 - Browser Chrome
 - Version Version 75.0.3770.100 (Official Build) (64-bit)

**Additional context**
It seems to work with `vue-cli` project (without `bento-starter`)

**Comment by kefranabg** [comment]
Hey ! 

I just tested it and it's working as expected on my laptop 🤔 

In the "expected behavior" part, you say that `VUE_APP_TITLE` should equal `Readable Changelog`,
but if `.env.local` exists, it will override `.env`. So this is right if you get `Readable Changelog Local`.

See [documentation](https://cli.vuejs.org/guide/mode-and-env.html#environment-variables) for more

**Comment by antoinecellier** [comment]
I solved my problem. There was a space at the end of my filename: `.env.local ` 😅

Thanks for ur help. I close issue.
